app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

Route::get('/', 'HomePageController@index')->name('home');

Route::get('catalog', 'CategoryController@catalog')->name('catalog');

Route::get('category/{slug}', 'CategoryController@category')->name('category')->where('slug', '[a-z0-9-]+');

// Route::get('categories/{slug}', 'CategoryController@category')->name('categories')->where('slug', '[a-z0-9-]+');

Route::get('product/{slug}', 'ProductController@show')->name('product')->where('slug', '[a-z0-9-]+');

Route::get('article/{slug}', 'ArticleController@show')->name('article')->where('slug', '[a-z0-9-]+');

Route::get('search', 'SearchController@search')->name('search');

// Route::get('luckycarp/terms', 'LuckyCarpCompetitionController@terms')->name('luckycarp.terms');
// Route::get('luckycarp/{source?}', 'LuckyCarpCompetitionController@index')->name('luckycarp.landing')->where('source', '[a-z0-9-]+');

Route::group(['prefix' => 'share'],
    function () {
        Route::get('{type}/{id}', 'ShareController@form')->name('share.form')->where('type', '(product)')->where('id', '[0-9]+');
        Route::post('send/{type}/{id}', 'ShareController@share')->name('share.request')->where('type', '(product)')->where('id', '[0-9]+');
    });

Route::group(['prefix' => 'contact'],
    function () {
        Route::get('/', 'ContactController@index')->name('contact.index');
        Route::post('/send', 'ContactController@send')->name('contact.request');
    });

Route::group(['prefix' => 'newsletter'],
    function () {
        Route::get('/subscribe', 'SubscriptionController@showSubscribe')->name('newsletter.subscribe');
        Route::get('/unsubscribe', 'SubscriptionController@showUnsubscribe')->name('newsletter.unsubscribe');
        Route::post('/subscribe', 'SubscriptionController@subscribe')->name('newsletter.action.subscribe');
        Route::post('/unsubscribe', 'SubscriptionController@unsubscribe')->name('newsletter.action.unsubscribe');
    });

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'nocache', 'namespace' => 'Auth'],
    function () {
        Route::get('/login', ['as' => 'login', 'uses' => 'AuthController@login']);
        Route::post('/authenticate', ['as' => 'authenticate', 'uses' => 'AuthController@authenticate']);
        Route::get('/logout', ['as' => 'logout', 'uses' => 'AuthController@logout']);
    });

// Route::group(['prefix' => 'combo-strike'],
//     function () {
//         // Route::get('', 'CompetitionController@index')->name('combostrike.competition');
//         Route::get('', 'CompetitionController@index')->name('combostrike.index');
//         Route::get('terms', 'CompetitionController@terms')->name('combostrike.terms');
//         Route::post('enter', 'CompetitionController@processEntry')->name('combostrike.process');
//     });

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'auth', 'namespace' => 'Dashboard'],
    function () {

        // Dashboard Index
        Route::get('/', ['as' => 'home', 'uses' => 'DashboardController@index']);

        /////////////////////////////////////////////////////
        // Site Admistrator
        Route::get('administrator', ['as' => 'administrator.index', 'uses' => 'AdminUserController@index']);

        // Images
        Route::match(['PUT', 'PATCH'], 'image/reorder', ['as' => 'image.reorder', 'uses' => 'ImageController@reorder']);

        /////////////////////////////////////////////////////
        // SiteFeature
        Route::get('sitefeature/datatable', ['as' => 'sitefeature.datatable', 'uses' => 'SiteFeatureController@dataTable']);
        Route::get('sitefeature/layout', ['as' => 'sitefeature.layout', 'uses' => 'SiteFeatureController@layout']);
        Route::match(['PUT', 'PATCH'], 'sitefeature/{sitefeature}/restore', ['as' => 'sitefeature.restore', 'uses' => 'SiteFeatureController@restore'])->where(['sitefeature' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'sitefeature/reorder', ['as' => 'sitefeature.reorder', 'uses' => 'SiteFeatureController@reorder']);
        Route::match(['PUT', 'PATCH'], 'sitefeature/{sitefeature}/togglepublish', ['as' => 'sitefeature.togglepublish', 'uses' => 'SiteFeatureController@togglePublish'])->where(['sitefeature' => '[0-9]+']);

        // SiteFeature Backgorund Image
        Route::get('sitefeature/{sitefeature}/image/create/background', ['as' => 'sitefeature.image.create.background', 'uses' => 'SiteFeatureController@createBackground'])->where(['sitefeature' => '[0-9]+']);
        Route::get('sitefeature/{sitefeature}/image/edit/background', ['as' => 'sitefeature.image.edit.background', 'uses' => 'SiteFeatureController@editBackground'])->where(['sitefeature' => '[0-9]+']);

        /////////////////////////////////////////////////////
        // Cateory
        Route::get('category/datatable', ['as' => 'category.datatable', 'uses' => 'CategoryController@dataTable']);
        Route::get('category/tree', ['as' => 'category.tree', 'uses' => 'CategoryController@tree']);
        Route::get('category/search', ['as' => 'category.search', 'uses' => 'CategoryController@search']);
        Route::match(['PUT', 'PATCH'], 'category/{category}/restore', ['as' => 'category.restore', 'uses' => 'CategoryController@restore'])->where(['category' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'category/reorder', ['as' => 'category.reorder', 'uses' => 'CategoryController@reorder']);
        // Cateory Hero Banner Images
        Route::get('category/{category}/image/create/hero-banner', ['as' => 'category.image.create.hero', 'uses' => 'CategoryController@createHeroBanner'])->where(['category' => '[0-9]+']);
        // Category Products
        Route::get('category/{category}/product', ['as' => 'category.product.index', 'uses' => 'CategoryController@products'])->where(['category' => '[0-9]+']);

        /////////////////////////////////////////////////////
        // FeatureSet
        Route::get('featureset/datatable', ['as' => 'featureset.datatable', 'uses' => 'FeatureSetController@dataTable']);
        Route::get('featureset/search', ['as' => 'featureset.search', 'uses' => 'FeatureSetController@search']);
        Route::get('featureset/sort', ['as' => 'featureset.sort', 'uses' => 'FeatureSetController@sort']);
        Route::match(['PUT', 'PATCH'], 'featureset/{featureset}/restore', ['as' => 'featureset.restore', 'uses' => 'FeatureSetController@restore'])->where(['featureset' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'featureset/reorder', ['as' => 'featureset.reorder', 'uses' => 'FeatureSetController@reorder']);
        // FeatureSet Features
        Route::get('featureset/{featureset}/feature', ['as' => 'featureset.feature.index', 'uses' => 'FeatureSetController@features'])->where(['featureset' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'featureset/{featureset}/feature/reorder', ['as' => 'featureset.feature.reorder', 'uses' => 'FeatureSetController@reorderFeatures'])->where(['featureset' => '[0-9]+']);

        /////////////////////////////////////////////////////
        // Product
        Route::get('product/datatable', ['as' => 'product.datatable', 'uses' => 'ProductController@dataTable']);
        Route::get('product/search', ['as' => 'product.search', 'uses' => 'ProductController@search']);
        Route::match(['PUT', 'PATCH'], 'product/{product}/restore', ['as' => 'product.restore', 'uses' => 'ProductController@restore'])->where(['product' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'product/{product}/togglepublish', ['as' => 'product.togglepublish', 'uses' => 'ProductController@togglePublish'])->where(['product' => '[0-9]+']);
        // Product Images
        Route::get('product/{product}/image', ['as' => 'product.image.index', 'uses' => 'ProductController@images'])->where(['product' => '[0-9]+']);
        Route::get('product/{product}/image/create/large', ['as' => 'product.image.create.large', 'uses' => 'ProductController@createLargeImage'])->where(['product' => '[0-9]+']);
        Route::get('product/{product}/image/create/thumbnail', ['as' => 'product.image.create.thumbnail', 'uses' => 'ProductController@createDisplayThumbnail'])->where(['product' => '[0-9]+']);
        Route::get('product/{product}/image/create/shareImage', ['as' => 'product.image.create.shareimage', 'uses' => 'ProductController@createShareImage'])->where(['product' => '[0-9]+']);
        // Product Categories
        Route::get('product/{product}/category', ['as' => 'product.category.index', 'uses' => 'ProductController@categories'])->where(['product' => '[0-9]+']);
        // Product Features
        Route::get('product/{product}/feature', ['as' => 'product.feature.index', 'uses' => 'ProductController@features'])->where(['product' => '[0-9]+']);

        /////////////////////////////////////////////////////
        // Variants
        Route::match(['PUT', 'PATCH'], 'product/{product}/variant/reorder', ['as' => 'product.variant.reorder', 'uses' => 'VariantController@reorder'])->where(['procuct' => '[0-9]+']);
        Route::get('product/{product}/variant/datatable', ['as' => 'product.variant.datatable', 'uses' => 'VariantController@dataTable'])->where(['procuct' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'product/{product}/variant/{variant}/restore', ['as' => 'product.variant.restore', 'uses' => 'VariantController@restore'])->where(['procuct' => '[0-9]+', 'variant' => '[0-9]+']);

        /////////////////////////////////////////////////////
        // Feature
        Route::get('feature/search', ['as' => 'feature.search', 'uses' => 'FeatureController@search']);

app/Http/Controllers/Dashboard/AdminUserController.php
<?php namespace Okuma\Http\Controllers\Dashboard;

use Illuminate\Support\Facades\View;
use Okuma\Http\Controllers\Controller;
use Okuma\Http\Requests\DashboardRequest;

class AdminUserController extends Controller
{

    public function index()
    {
        $view = View::make('dashboard.adminuser.index');
        return $view;
    }

    public function updatePassword(DashboardRequest $request)
    {

    }

}

app/Http/Controllers/Dashboard/BackupController.php
<?php namespace Okuma\Http\Controllers\Dashboard;

use Carbon\Carbon;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\View;
use Okuma\Http\Controllers\Controller;

class BackupController extends Controller
{

    public function index()
    {
        $directory = Config::get('laravel-backup.backup.name');

        $disk = Storage::disk('localbackup');

        $files = $disk->files($directory);
        $files = array_reverse($files);

        $backups = [];

        $now = Carbon::now();

        foreach ($files as $file) {

            if (ends_with($file, '.zip')) {

                $filename = basename($file, '.zip');

                $date = Carbon::createFromFormat('Y-m-d-His', $filename);

                $backup = [
                    'filename' => $filename,
                    'age' => $date->diffForHumans($now, true),
                    'size' => $this->formatBytes($disk->size($file)),
                    'fullpath' => basename($file),
                ];

                array_push($backups, $backup);
            }
        }

        $view = View::make('dashboard.backup.index')->with(['backups' => $backups]);

        return $view;
    }

    protected function formatBytes($bytes, $precision = 2)
    {
        $units = array('B', 'KB', 'MB', 'GB', 'TB');

        $bytes = max($bytes, 0);
        $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
        $pow = min($pow, count($units) - 1);

        // Uncomment one of the following alternatives
        // $bytes /= pow(1024, $pow);
        $bytes /= (1 << (10 * $pow));

        return round($bytes, $precision) . ' ' . $units[$pow];
    }

    public function destroy($file)
    {
        $directory = Config::get('laravel-backup.backup.name');

        if (Storage::disk('localbackup')->exists($directory . '/' . $file)) {
            Storage::disk('localbackup')->delete($directory . '/' . $file);
        }

        return Response::json(['level' => 'success', 'icon' => 'fa fa-fw fa-lg fa-check-circle-o', 'title' => 'Success: ', 'message' => "<em>Backup</em> destroyed."], 200);
    }

    public function create()
    {
        $exitCode = Artisan::call('backup:run');

        Session::flash('status', 'Backup started. Please be patient.');

        return redirect()->route('dashboard.backup.index');
    }

    public function clean()
    {
        $exitCode = Artisan::call('backup:clean');

        Session::flash('status', 'Backups queued for cleaning.');

        return redirect()->route('dashboard.backup.index');
    }

    public function download($file)
    {
        $directory = Config::get('laravel-backup.backup.name');

        $disk = Storage::disk('localbackup');

        if ($disk->exists($directory . '/' . $file)) {

            $path = $disk->getDriver()->getAdapter()->getPathPrefix();

            $size = $disk->size($directory . '/' . $file);

            return Response::download($path . $directory . '/' . $file, $file, ['Content-Length: ' . $size]);
        }

        abort(404);
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php namespace Okuma\Http\Controllers\Dashboard;

use Illuminate\Support\Facades\View;
use Okuma\Http\Controllers\Controller;

class DashboardController extends Controller
{

    public function index()
    {
        $view = View::make('dashboard.master');
        return $view;
    }

    public function phpinfo()
    {
        $view = View::make('dashboard.pages.phpinfo');
        return $view;
    }

}

app/Http/Controllers/Dashboard/LogViewerController.php
<?php namespace Okuma\Http\Controllers\Dashboard;

use Illuminate\Support\Facades\View;
use Okuma\Http\Controllers\Controller;

class LogViewerController extends Controller
{

    public function index()
    {
        $view = View::make('dashboard.logs.index');

        return $view;
    }
}

resources/views/dashboard/sitefeature/create.blade.php
@extends('dashboard.master')

@section('pageTitle')
SiteFeature - Create New
@endsection

@section('pageHeader')
Site Feature - Create New
@endsection

@section('stylesheets')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.15.35/css/bootstrap-datetimepicker.min.css">
@endsection

@section('content')
<div class="row">
	<div class="col-sm-12">
		<h3 class="text-muted">Site Feature Details</h3>
		{!! Form::open(['route' => ['dashboard.sitefeature.store'], 'method'=> 'POST']) !!}

		<div class="form-group @if($errors->has('title')) has-error @endif">
			{!! Form::label('title', 'Title: ' . $errors->first('title'), array('class' => 'control-label')) !!}
			{!! Form::text('title', null , ['class'=>'form-control', 'placeholder'=>'Site Feature Title', 'maxlength' => 255])!!}
			<p class="help-block"><span class="label label-default">Optional</span> The <strong>Title</strong> of a Site Feature. Always visible. Supports <code>&lt;em&gt;</code> and <code>&lt;strong&gt;</code> tags.</p>
		</div>

		<div class="form-group @if($errors->has('body')) has-error @endif">
			{!! Form::label('body', 'Body: ' . $errors->first('body'), array('class' => 'control-label')) !!}
			{!! Form::textArea('body', null , [ 'class'=>'form-control', 'placeholder'=>'Site Feature Body', 'rows'=> 10 ])!!}
			<p class="help-block"><span class="label label-default">Optional</span> The <strong>Body</strong> copy that appears when hovering over a Site Feature. Supports <code>&lt;html&gt;</code> tags.</p>
		</div>

		<div class="form-group @if($errors->has('button_label')) has-error @endif">
			{!! Form::label('button_label', 'Button Label: ' . $errors->first('button_label'), array('class' => 'control-label')) !!}
			{!! Form::text('button_label', 'View More' , ['class'=>'form-control', 'placeholder'=>'Site Feature Button Label', 'maxlength' => 64])!!}
			<p class="help-block"><span class="label label-default">Optional</span> The <strong>Button Label</strong>. Defaults to <em>View More</em>.</p>
		</div>

		<div class="form-group @if($errors->has('link')) has-error @endif">
			{!! Form::label('link', 'Link: ' . $errors->first('link'), array('class' => 'control-label')) !!}
			{!! Form::text('link', null , ['class'=>'form-control', 'placeholder'=>'Site Feature Link', 'maxlength' => 2000])!!}
			<p class="help-block"><span class="label label-info">Required</span> The <strong>URL</strong> to navigate to on click.</p>
		</div>

		<div class="form-group @if($errors->has('column_size')) has-error @endif">
			{!! Form::label('column_size', 'Column Size: ' . $errors->first('column_size'), array('class' => 'control-label')) !!}
			{!! Form::select('column_size',  $columnSizes, null, ['id'=>'column_size', 'class'=>'form-control selectpicker', 'title'=>'Select Column Size'])!!}
			<p class="help-block"><span class="label label-info">Required</span> The <strong>Column Size Large</strong>. Determines width of the Site Feature for Large (Desktop) screen sizes. Scales automatically for other screen resolutions</p>
		</div>

		<div class="form-group @if($errors->has('display_class')) has-error @endif">
			{!! Form::label('display_class', 'Display Class: ' . $errors->first('display_class'), array('class' => 'control-label')) !!}
			{!! Form::select('display_class',  $displayClasses, null, ['id'=>'display_class', 'class'=>'form-control selectpicker', 'title'=>'Select Display Class'])!!}
			<p class="help-block"<span class="label label-default">Optional</span> <strong>Display Class</strong>. Changes the appearance of the Site Feature.</p>
		</div>

		<div class="form-group @if($errors->has('published_at')) has-error @endif">
			{!! Form::label('published_at', 'Publish Date: ' . $errors->first('published_at'), array('class' => 'control-label')) !!}
			<div class="input-group date" id="published_at_datepicker">
				<span class="input-group-addon"><i class="fa fa-fw fa-calendar"></i></span>
				{!! Form::text('published_at', null , ['class'=>'form-control', 'placeholder'=>'Publish Date'])!!}
			</div>
			<p class="help-block"><span class="label label-default">Optional</span> <strong>Publish Date</strong> of this Site Feature. Only Site Feature with a Publish Date set after the current Date will be visible. Leave empty to save as Draft</p>
		</div>

		<a href="@if(Session::has('redirect')) {!! Session::get('redirect') !!} @else {{ route('dashboard.sitefeature.index') }} @endif" class="btn btn-default"><i class="fa fa-fw fa-lg fa-times-circle"></i> Cancel</a>
		<button type="submit" class="btn btn-primary"><i class="fa fa-fw fa-lg fa-bolt"></i> Create</button>

		{!! Form::close() !!}
	</div>
</div>
@endsection

@section('scripts')
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.15.35/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="{{ URL::asset('dashboard_assets/js/okuma/sitefeature.min.js') }}"></script>
@endsection

resources/views/dashboard/sitefeature/edit.blade.php
@extends('dashboard.master')

@section('pageTitle')
SiteFeature - Edit
@endsection

@section('pageHeader')
Site Feature - Edit
@endsection

@section('stylesheets')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.15.35/css/bootstrap-datetimepicker.min.css">
@endsection

@section('content')
<div class="row">
	<div class="col-sm-12">
		<table class="table table-bordered">
			<thead>
				<tr class="@if($siteFeature->trashed()) warning @else info @endif" >
					<th>ID</th>
					<th>Title</th>
					<th>Position</th>
					<th>Created At</th>
					<th>Updated At</th>
					<th>Published On</th>
					<th>Trashed</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>{{ $siteFeature->id }}</td>
					<td><span class="truncate" style="max-width:200px">{!! $siteFeature->title !!}</span></td>
					<td>{{ $siteFeature->position }}</td>
					<td>{{ $siteFeature->created_at }}</td>
					<td>{{ $siteFeature->updated_at }}</td>
					<td>@if($siteFeature->isPublished()) <span class="label label-success">{{ $siteFeature->published_at }}</span> @else <span class="label label-default">Unpublished</span> @endif</td>
					<td>@if($siteFeature->trashed()) <span class="label label-warning">TRUE</span> @else <span class="label label-default">FALSE</span> @endif</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<div class="well well-lg">
			@if(isset($siteFeature->background))
			<img src="{{ URL::asset($siteFeature->background->path) }}" class="img-responsive" data-image-id="{{ $siteFeature->background->id }}">
			<br/>
			<div>
				<span class="label label-primary">#{{ $siteFeature->background->id }}</span>
				<span class="label label-info">{{ $siteFeature->background->updated_at }}</span>
			</div>
			<h5>{{ $siteFeature->background->title }}</h5>
			<div class="btn-group btn-group-sm model-actions">
				@include('dashboard.components.buttons.edit', ['url'=> URL::route('dashboard.sitefeature.image.edit.background', ['image'=>$siteFeature->id])])
				@include('dashboard.components.buttons.destroy', ['url'=> URL::route('dashboard.image.destroy', ['image'=>$siteFeature->background->id])])
			</div>
			@else
			<a class="btn btn-primary" href="{{ route('dashboard.sitefeature.image.create.background',['sitefeature'=>$siteFeature->id]) }}"><i class="fa fa-lg fa-fw fa-picture-o"></i> Set Background</a>
			@endif
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<h3 class="text-muted">Site Feature Details</h3>

		{!! Form::model($siteFeature, ['route' => ['dashboard.sitefeature.update', $siteFeature->id], 'method'=> 'PATCH']) !!}

		<div class="form-group @if($errors->has('title')) has-error @endif">
			{!! Form::label('title', 'Title: ' . $errors->first('title'), array('class' => 'control-label')) !!}
			{!! Form::text('title', null , ['class'=>'form-control', 'placeholder'=>'Site Feature Title', 'maxlength' => 255])!!}
			<p class="help-block">The <span class="label label-default">Optional</span> <strong>Title</strong> of a Site Feature. Always visible. Supports <code>&lt;em&gt;</code> and <code>&lt;strong&gt;</code> tags.</p>
		</div>

		<div class="form-group @if($errors->has('body')) has-error @endif">
			{!! Form::label('body', 'Body: ' . $errors->first('body'), array('class' => 'control-label')) !!}
			{!! Form::textArea('body', null , [ 'class'=>'form-control', 'placeholder'=>'Site Feature Body', 'rows'=> 10 ])!!}
			<p class="help-block">The <span class="label label-default">Optional</span> <strong>Body</strong> copy that appears when hovering over a Site Feature. Supports <code>&lt;html&gt;</code> tags.</p>
		</div>

		<div class="form-group @if($errors->has('button_label')) has-error @endif">
			{!! Form::label('button_label', 'Button Label: ' . $errors->first('button_label'), array('class' => 'control-label')) !!}
			{!! Form::text('button_label', null , ['class'=>'form-control', 'placeholder'=>'Site Feature Button Label', 'maxlength' => 64])!!}
			<p class="help-block">The <span class="label label-default">Optional</span> <strong>Button Label</strong>. Defaults to <em>View More</em>.</p>
		</div>

		<div class="form-group @if($errors->has('link')) has-error @endif">
			{!! Form::label('link', 'Link: ' . $errors->first('link'), array('class' => 'control-label')) !!}
			{!! Form::text('link', null , ['class'=>'form-control', 'placeholder'=>'Site Feature Link', 'maxlength' => 2000])!!}
			<p class="help-block">The <span class="label label-info">Required</span> <strong>URL</strong> to navigate to on click.</p>
		</div>

		<?php
$column_size = old('column_size');
if (!isset($column_size)) {
    $column_size = explode(' ', $siteFeature->column_size);
    $column_size = array_pop($column_size);
}
?>

		<div class="form-group @if($errors->has('column_size')) has-error @endif">
			{!! Form::label('column_size', 'Column Size: ' . $errors->first('column_size'), array('class' => 'control-label')) !!}
			{!! Form::select('column_size',  $columnSizes, $column_size, ['id'=>'column_size', 'class'=>'form-control selectpicker', 'title'=>'Select Column Size'])!!}
			<p class="help-block">The <span class="label label-info">Required</span> <strong>Column Size Large</strong>. Determines width of the Site Feature for Large (Desktop) screen sizes. Scales automatically for other screen resolutions <em>{{  $siteFeature->getOriginal('column_size') }}</em></p>
		</div>

		<div class="form-group @if($errors->has('display_class')) has-error @endif">
			{!! Form::label('display_class', 'Display Class: ' . $errors->first('display_class'), array('class' => 'control-label')) !!}
			{!! Form::select('display_class',  $displayClasses, null, ['id'=>'display_class', 'class'=>'form-control selectpicker', 'title'=>'Select Display Class'])!!}
			<p class="help-block"<span class="label label-default">Optional</span> <strong>Display Class</strong>. Changes the appearance of the Site Feature.</p>
		</div>

		<div class="form-group @if($errors->has('published_at')) has-error @endif">
			{!! Form::label('published_at', 'Publish Date: ' . $errors->first('published_at'), array('class' => 'control-label')) !!}
			<div class="input-group date" id="published_at_datepicker">
				<span class="input-group-addon"><i class="fa fa-fw fa-calendar"></i></span>
				{!! Form::text('published_at', null , ['class'=>'form-control', 'placeholder'=>'Publish Date'])!!}
			</div>
			<p class="help-block"><span class="label label-default">optional</span> <strong>Publish Date</strong> of this Site Feature. Only Site Feature with a Publish Date set after the current Date will be visible. Leave empty to save as Draft</p>
		</div>

		<div class="form-group">
			<a href="@if(Session::has('redirect')) {!! Session::get('redirect') !!} @else {{ route('dashboard.sitefeature.index') }} @endif" class="btn btn-default"><i class="fa fa-fw fa-lg fa-times-circle"></i> Cancel</a>
			<button type="submit" class="btn btn-primary"><i class="fa fa-fw fa-lg fa-save"></i> Save Changes</button>
		</div>

		{!! Form::close() !!}

	</div>
</div>
@endsection

@section('scripts')
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.15.35/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="{{ URL::asset('dashboard_assets/js/okuma/sitefeature.min.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('dashboard_assets/js/okuma/sitefeature.min.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('dashboard_assets/js/okuma/model.actions.min.js') }}"></script>
@endsection