app/Http/routes.php
Route::get('catalog', 'CategoryController@catalog')->name('catalog');

Route::get('category/{slug}', 'CategoryController@category')->name('category')->where('slug', '[a-z0-9-]+');

// Route::get('categories/{slug}', 'CategoryController@category')->name('categories')->where('slug', '[a-z0-9-]+');

Route::get('product/{slug}', 'ProductController@show')->name('product')->where('slug', '[a-z0-9-]+');

Route::get('article/{slug}', 'ArticleController@show')->name('article')->where('slug', '[a-z0-9-]+');

Route::get('search', 'SearchController@search')->name('search');

// Route::get('luckycarp/terms', 'LuckyCarpCompetitionController@terms')->name('luckycarp.terms');
// Route::get('luckycarp/{source?}', 'LuckyCarpCompetitionController@index')->name('luckycarp.landing')->where('source', '[a-z0-9-]+');

Route::group(['prefix' => 'share'],
    function () {
        Route::get('{type}/{id}', 'ShareController@form')->name('share.form')->where('type', '(product)')->where('id', '[0-9]+');
        Route::post('send/{type}/{id}', 'ShareController@share')->name('share.request')->where('type', '(product)')->where('id', '[0-9]+');
    });

Route::group(['prefix' => 'contact'],
    function () {
        Route::get('/', 'ContactController@index')->name('contact.index');
        Route::post('/send', 'ContactController@send')->name('contact.request');
    });

Route::group(['prefix' => 'newsletter'],
    function () {
        Route::get('/subscribe', 'SubscriptionController@showSubscribe')->name('newsletter.subscribe');
        Route::get('/unsubscribe', 'SubscriptionController@showUnsubscribe')->name('newsletter.unsubscribe');
        Route::post('/subscribe', 'SubscriptionController@subscribe')->name('newsletter.action.subscribe');
        Route::post('/unsubscribe', 'SubscriptionController@unsubscribe')->name('newsletter.action.unsubscribe');
    });

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'nocache', 'namespace' => 'Auth'],
    function () {
        Route::get('/login', ['as' => 'login', 'uses' => 'AuthController@login']);
        Route::post('/authenticate', ['as' => 'authenticate', 'uses' => 'AuthController@authenticate']);
        Route::get('/logout', ['as' => 'logout', 'uses' => 'AuthController@logout']);
    });

// Route::group(['prefix' => 'combo-strike'],
//     function () {
//         // Route::get('', 'CompetitionController@index')->name('combostrike.competition');
//         Route::get('', 'CompetitionController@index')->name('combostrike.index');
//         Route::get('terms', 'CompetitionController@terms')->name('combostrike.terms');
//         Route::post('enter', 'CompetitionController@processEntry')->name('combostrike.process');
//     });

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'auth', 'namespace' => 'Dashboard'],
    function () {

        // Dashboard Index
        Route::get('/', ['as' => 'home', 'uses' => 'DashboardController@index']);

        /////////////////////////////////////////////////////
        // Site Admistrator
        Route::get('administrator', ['as' => 'administrator.index', 'uses' => 'AdminUserController@index']);

        // Images
        Route::match(['PUT', 'PATCH'], 'image/reorder', ['as' => 'image.reorder', 'uses' => 'ImageController@reorder']);

        /////////////////////////////////////////////////////
        // SiteFeature
        Route::get('sitefeature/datatable', ['as' => 'sitefeature.datatable', 'uses' => 'SiteFeatureController@dataTable']);
        Route::get('sitefeature/layout', ['as' => 'sitefeature.layout', 'uses' => 'SiteFeatureController@layout']);
        Route::match(['PUT', 'PATCH'], 'sitefeature/{sitefeature}/restore', ['as' => 'sitefeature.restore', 'uses' => 'SiteFeatureController@restore'])->where(['sitefeature' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'sitefeature/reorder', ['as' => 'sitefeature.reorder', 'uses' => 'SiteFeatureController@reorder']);
        Route::match(['PUT', 'PATCH'], 'sitefeature/{sitefeature}/togglepublish', ['as' => 'sitefeature.togglepublish', 'uses' => 'SiteFeatureController@togglePublish'])->where(['sitefeature' => '[0-9]+']);

        // SiteFeature Backgorund Image
        Route::get('sitefeature/{sitefeature}/image/create/background', ['as' => 'sitefeature.image.create.background', 'uses' => 'SiteFeatureController@createBackground'])->where(['sitefeature' => '[0-9]+']);
        Route::get('sitefeature/{sitefeature}/image/edit/background', ['as' => 'sitefeature.image.edit.background', 'uses' => 'SiteFeatureController@editBackground'])->where(['sitefeature' => '[0-9]+']);

        /////////////////////////////////////////////////////
        // Cateory
        Route::get('category/datatable', ['as' => 'category.datatable', 'uses' => 'CategoryController@dataTable']);
        Route::get('category/tree', ['as' => 'category.tree', 'uses' => 'CategoryController@tree']);
        Route::get('category/search', ['as' => 'category.search', 'uses' => 'CategoryController@search']);
        Route::match(['PUT', 'PATCH'], 'category/{category}/restore', ['as' => 'category.restore', 'uses' => 'CategoryController@restore'])->where(['category' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'category/reorder', ['as' => 'category.reorder', 'uses' => 'CategoryController@reorder']);
        // Cateory Hero Banner Images
        Route::get('category/{category}/image/create/hero-banner', ['as' => 'category.image.create.hero', 'uses' => 'CategoryController@createHeroBanner'])->where(['category' => '[0-9]+']);
        // Category Products
        Route::get('category/{category}/product', ['as' => 'category.product.index', 'uses' => 'CategoryController@products'])->where(['category' => '[0-9]+']);

        /////////////////////////////////////////////////////
        // FeatureSet
        Route::get('featureset/datatable', ['as' => 'featureset.datatable', 'uses' => 'FeatureSetController@dataTable']);
        Route::get('featureset/search', ['as' => 'featureset.search', 'uses' => 'FeatureSetController@search']);
        Route::get('featureset/sort', ['as' => 'featureset.sort', 'uses' => 'FeatureSetController@sort']);
        Route::match(['PUT', 'PATCH'], 'featureset/{featureset}/restore', ['as' => 'featureset.restore', 'uses' => 'FeatureSetController@restore'])->where(['featureset' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'featureset/reorder', ['as' => 'featureset.reorder', 'uses' => 'FeatureSetController@reorder']);
        // FeatureSet Features
        Route::get('featureset/{featureset}/feature', ['as' => 'featureset.feature.index', 'uses' => 'FeatureSetController@features'])->where(['featureset' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'featureset/{featureset}/feature/reorder', ['as' => 'featureset.feature.reorder', 'uses' => 'FeatureSetController@reorderFeatures'])->where(['featureset' => '[0-9]+']);

        /////////////////////////////////////////////////////
        // Product
        Route::get('product/datatable', ['as' => 'product.datatable', 'uses' => 'ProductController@dataTable']);
        Route::get('product/search', ['as' => 'product.search', 'uses' => 'ProductController@search']);
        Route::match(['PUT', 'PATCH'], 'product/{product}/restore', ['as' => 'product.restore', 'uses' => 'ProductController@restore'])->where(['product' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'product/{product}/togglepublish', ['as' => 'product.togglepublish', 'uses' => 'ProductController@togglePublish'])->where(['product' => '[0-9]+']);
        // Product Images
        Route::get('product/{product}/image', ['as' => 'product.image.index', 'uses' => 'ProductController@images'])->where(['product' => '[0-9]+']);
        Route::get('product/{product}/image/create/large', ['as' => 'product.image.create.large', 'uses' => 'ProductController@createLargeImage'])->where(['product' => '[0-9]+']);
        Route::get('product/{product}/image/create/thumbnail', ['as' => 'product.image.create.thumbnail', 'uses' => 'ProductController@createDisplayThumbnail'])->where(['product' => '[0-9]+']);
        Route::get('product/{product}/image/create/shareImage', ['as' => 'product.image.create.shareimage', 'uses' => 'ProductController@createShareImage'])->where(['product' => '[0-9]+']);
        // Product Categories
        Route::get('product/{product}/category', ['as' => 'product.category.index', 'uses' => 'ProductController@categories'])->where(['product' => '[0-9]+']);
        // Product Features
        Route::get('product/{product}/feature', ['as' => 'product.feature.index', 'uses' => 'ProductController@features'])->where(['product' => '[0-9]+']);

        /////////////////////////////////////////////////////
        // Variants
        Route::match(['PUT', 'PATCH'], 'product/{product}/variant/reorder', ['as' => 'product.variant.reorder', 'uses' => 'VariantController@reorder'])->where(['procuct' => '[0-9]+']);
        Route::get('product/{product}/variant/datatable', ['as' => 'product.variant.datatable', 'uses' => 'VariantController@dataTable'])->where(['procuct' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'product/{product}/variant/{variant}/restore', ['as' => 'product.variant.restore', 'uses' => 'VariantController@restore'])->where(['procuct' => '[0-9]+', 'variant' => '[0-9]+']);

        /////////////////////////////////////////////////////
        // Feature
        Route::get('feature/search', ['as' => 'feature.search', 'uses' => 'FeatureController@search']);
        Route::get('feature/datatable', ['as' => 'feature.datatable', 'uses' => 'FeatureController@dataTable']);
        // Route::match(['PUT', 'PATCH'], 'feature/reorder', ['as' => 'feature.reorder', 'uses' => 'FeatureController@reorder']);
        Route::get('feature/{feature}/image/create/icon', ['as' => 'feature.image.create.icon', 'uses' => 'FeatureController@createIcon'])->where(['feature' => '[0-9]+']);

app/Models/SiteFeature.php
<?php namespace Okuma\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Okuma\Database\Eloquent\Published;
use Okuma\Models\Image;

class SiteFeature extends Model
{
    use Published;
    use SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'site_features';

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id', 'published_at', 'created_at', 'updated_at', 'deleted_at'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['published_at', 'created_at', 'updated_at', 'deleted_at'];

    /**
     * The class name to be used in polymorphic relations.
     *
     * @var string
     */
    // protected $morphClass = 'SiteFeature';

    public function background()
    {
        return $this->morphOne(Image::class, 'imageable');
    }

    // /**
    //  * Get the column size for all screen resolutions.
    //  *
    //  * @param  string  $value
    //  * @return string
    //  */
    // public function getFirstNameAttribute($value)
    // {
    //     switch ($value) {
    //         case 'large-4':
    //             return 'small-12 medium-6 large-4';
    //             break;

    //         case 'large-6':
    //             return 'small-12 medium-6 large-6';
    //             break;

    //         case 'large-8':
    //             return 'small-12 medium-12 large-8';
    //             break;

    //         case 'large-12':
    //             return 'small-12 medium-12 large-12';
    //             break;

    //         default:
    //             return $value;
    //             break;
    //     }
    // }

    public function getImageType()
    {
        $columnSize = $this->column_size;

        $columnClasses = explode(' ', $columnSize);

        $columnSize = array_pop($columnClasses);

        switch ($columnSize) {
            case 'large-4':
                return 'site_feature_4_bg';
                break;

            case 'large-6':
                return 'site_feature_6_bg';
                break;

            case 'large-8':
                return 'site_feature_8_bg';
                break;

            case 'large-12':
                return 'site_feature_12_bg';
                break;

            default:
                return 'site_feature_hero_bg';
                break;
        }
    }

    //     public function calcBGImageWidth()
    // {
    //     $columnSize = $this->column_size;

    //     $columnClasses = $columnSize . split(' ');

    //     $columnSize = array_pop($columnClasses);

    //     switch ($columnSize) {
    //         case 'large-4':
    //             return 400;
    //             break;

    //         case 'large-6':
    //             return 600;
    //             break;

    //         case 'large-8':
    //             return 800;
    //             break;

    //         case 'large-12':
    //             return 1200;
    //             break;

    //         default:
    //             return 1920;
    //             break;
    //     }
    // }

    public function bootstrapColumnSize()
    {

        $bootstrap = $this->column_size;

        $bootstrap = str_replace('small-', 'col-sm-', $bootstrap);
        $bootstrap = str_replace('medium-', 'col-md-', $bootstrap);
        $bootstrap = str_replace('large-', 'col-lg-', $bootstrap);

        return $bootstrap;
    }

}

resources/views/dashboard/sitefeature/index/layout.blade.php
@extends('dashboard.common.tab.index')

@section('pageTitle')
@parent
 - Layout
@endsection

@section('pageHeader')
@parent
- Layout
@endsection

@section('controls')
@parent
<form action="{{ route('dashboard.sitefeature.reorder') }}" method="POST" class="inline-block" id="sitefeatures-reorder-form">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <input type="hidden" name="_method" value="PATCH" />
    <input type="hidden" name="orderables" value=""/>
    <button class="btn btn-primary" type="submit"><i class="fa fa-fw fa-lg fa-save"></i> Save Layout</button>
</form>

<a href="{{ route('dashboard.sitefeature.layout') }}" class="btn btn-default"><i class="fa fa-fw fa-lg fa-undo"></i> Reset Layout</a>
@endsection

@section('tabContent')

@if (isset($hero))
<?php $routeParams = ['sitefeature' => $hero->id];?>
<div class="row">
    <div class="col-sm-12 hero">
        <div class="site-feature-wrapper">
            <figure class="site-feature {{ $hero->display_class }}">

                @if(isset($hero->background))
                    <div class="site-feature-bg" style="background-image: url({{ URL::asset($hero->background->path) }})"></div>
                @endif

                <figcaption>
                    <div>
                        @if(isset($hero->title))
                            <h2 class="site-feature-title">{{ $hero->title }}</h2>
                        @endif
                        @if(isset($hero->body))
                            <div class="site-feature-body">{{ $hero->body }}</div>
                        @endif
                    </div>

                    @if(isset($hero->link) && isset($hero->button_label))
                        <a href="#" class="site-feature-button">{{ $hero->button_label }}</a>
                    @endif

                </figcaption>
                <div class="btn-group btn-group-sm model-actions">

                    @include('dashboard.components.buttons.edit', ['url'=> URL::route('dashboard.sitefeature.edit', $routeParams)])

                    @if($hero->isPublished())
                        @include('dashboard.components.buttons.unpublish', ['url'=> URL::route('dashboard.sitefeature.togglepublish', $routeParams)])
                    @else
                        @include('dashboard.components.buttons.publish', ['url'=> URL::route('dashboard.sitefeature.togglepublish', $routeParams)])
                    @endif

                    @if($hero->trashed())
                        @include('dashboard.components.buttons.destroy', ['url'=> URL::route('dashboard.sitefeature.destroy', $routeParams)])
                        @include('dashboard.components.buttons.restore', ['url'=> URL::route('dashboard.sitefeature.restore', $routeParams)])
                    @else
                        @include('dashboard.components.buttons.trash', ['url'=> URL::route('dashboard.sitefeature.destroy', $routeParams)])
                    @endif
                </div>
            </figure>
        </div>
    </div>
</div>

@endif

<div class="container" id ="sitefeature-container">
    <div class="row no-gutter sortable-grid">
        @foreach ($siteFeatures as $feature)
        <?php $routeParams = ['sitefeature' => $feature->id];?>
        <div class="{{ $feature->bootstrapColumnSize() }} sortable-item" data-id="{{ $feature->id }}">
            <div class="site-feature-wrapper">
                <figure class="site-feature  {{ $feature->display_class }}">

                    @if(isset($feature->background))
                        <div class="site-feature-bg" style="background-image: url({{ URL::asset($feature->background->path) }})"></div>
                    @endif

                    <figcaption>
                        <div>
                            @if(isset($feature->title))
                                <h2 class="site-feature-title">{{ $feature->title }}</h2>
                            @endif
                            @if(isset($feature->body))
                                <div class="site-feature-body">{{ $feature->body }}</div>
                            @endif
                        </div>

                        @if(isset($feature->link) && isset($feature->button_label))
                            <a href="#" class="site-feature-button">{{ $feature->button_label }}</a>
                        @endif

                    </figcaption>

                    <div class="btn-group btn-group-sm model-actions">
                        @include('dashboard.components.buttons.edit', ['url'=> URL::route('dashboard.sitefeature.edit', $routeParams)])

                        @if($feature->isPublished())
                            @include('dashboard.components.buttons.unpublish', ['url'=> URL::route('dashboard.sitefeature.togglepublish', $routeParams)])
                        @else
                            @include('dashboard.components.buttons.publish', ['url'=> URL::route('dashboard.sitefeature.togglepublish', $routeParams)])
                        @endif

                        @if($feature->trashed())
                            @include('dashboard.components.buttons.destroy', ['url'=> URL::route('dashboard.sitefeature.destroy', $routeParams)])
                            @include('dashboard.components.buttons.restore', ['url'=> URL::route('dashboard.sitefeature.restore', $routeParams)])
                        @else
                            @include('dashboard.components.buttons.trash', ['url'=> URL::route('dashboard.sitefeature.destroy', $routeParams)])
                        @endif
                    </div>
                </figure>
            </div>
        </div>
        @endforeach
    </div>
</div>
@endsection


@section('scripts')
    <script type="text/javascript" src="{{ URL::asset('dashboard_assets/js/vendor/jquery-sortable-min.js') }}"></script>
    <script type="text/javascript" src="{{ URL::asset('dashboard_assets/js/okuma/model.actions.min.js') }}"></script>
    <script type="text/javascript" src="{{ URL::asset('dashboard_assets/js/okuma/sortable.grid.min.js') }}"></script>
    <script type="text/javascript" src="{{ URL::asset('dashboard_assets/js/okuma/sitefeature.min.js') }}"></script>
@endsection

resources/views/dashboard/sitefeature/index/tabs.blade.php
<li class="@if($routeName === $baseRoute.'.layout') active @endif">
	<a href="{{ route($baseRoute.'.layout') }}"><i class="fa fa-fw fa-lg fa-th-large"></i> Sort</a>
</li>