app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

Route::get('/', 'HomePageController@index')->name('home');

Route::get('catalog', 'CategoryController@catalog')->name('catalog');

Route::get('category/{slug}', 'CategoryController@category')->name('category')->where('slug', '[a-z0-9-]+');

// Route::get('categories/{slug}', 'CategoryController@category')->name('categories')->where('slug', '[a-z0-9-]+');

Route::get('product/{slug}', 'ProductController@show')->name('product')->where('slug', '[a-z0-9-]+');

Route::get('article/{slug}', 'ArticleController@show')->name('article')->where('slug', '[a-z0-9-]+');

Route::get('search', 'SearchController@search')->name('search');

// Route::get('luckycarp/terms', 'LuckyCarpCompetitionController@terms')->name('luckycarp.terms');
// Route::get('luckycarp/{source?}', 'LuckyCarpCompetitionController@index')->name('luckycarp.landing')->where('source', '[a-z0-9-]+');

Route::group(['prefix' => 'share'],
    function () {
        Route::get('{type}/{id}', 'ShareController@form')->name('share.form')->where('type', '(product)')->where('id', '[0-9]+');
        Route::post('send/{type}/{id}', 'ShareController@share')->name('share.request')->where('type', '(product)')->where('id', '[0-9]+');
    });

Route::group(['prefix' => 'contact'],
    function () {
        Route::get('/', 'ContactController@index')->name('contact.index');
        Route::post('/send', 'ContactController@send')->name('contact.request');
    });

Route::group(['prefix' => 'newsletter'],
    function () {
        Route::get('/subscribe', 'SubscriptionController@showSubscribe')->name('newsletter.subscribe');
        Route::get('/unsubscribe', 'SubscriptionController@showUnsubscribe')->name('newsletter.unsubscribe');
        Route::post('/subscribe', 'SubscriptionController@subscribe')->name('newsletter.action.subscribe');
        Route::post('/unsubscribe', 'SubscriptionController@unsubscribe')->name('newsletter.action.unsubscribe');
    });

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'nocache', 'namespace' => 'Auth'],
    function () {
        Route::get('/login', ['as' => 'login', 'uses' => 'AuthController@login']);
        Route::post('/authenticate', ['as' => 'authenticate', 'uses' => 'AuthController@authenticate']);
        Route::get('/logout', ['as' => 'logout', 'uses' => 'AuthController@logout']);
    });

// Route::group(['prefix' => 'combo-strike'],
//     function () {
//         // Route::get('', 'CompetitionController@index')->name('combostrike.competition');
//         Route::get('', 'CompetitionController@index')->name('combostrike.index');
//         Route::get('terms', 'CompetitionController@terms')->name('combostrike.terms');
//         Route::post('enter', 'CompetitionController@processEntry')->name('combostrike.process');
//     });

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'auth', 'namespace' => 'Dashboard'],
    function () {

        // Dashboard Index
        Route::get('/', ['as' => 'home', 'uses' => 'DashboardController@index']);

        /////////////////////////////////////////////////////
        // Site Admistrator
        Route::get('administrator', ['as' => 'administrator.index', 'uses' => 'AdminUserController@index']);

        // Images
        Route::match(['PUT', 'PATCH'], 'image/reorder', ['as' => 'image.reorder', 'uses' => 'ImageController@reorder']);

        /////////////////////////////////////////////////////
        // SiteFeature
        Route::get('sitefeature/datatable', ['as' => 'sitefeature.datatable', 'uses' => 'SiteFeatureController@dataTable']);
        Route::get('sitefeature/layout', ['as' => 'sitefeature.layout', 'uses' => 'SiteFeatureController@layout']);
        Route::match(['PUT', 'PATCH'], 'sitefeature/{sitefeature}/restore', ['as' => 'sitefeature.restore', 'uses' => 'SiteFeatureController@restore'])->where(['sitefeature' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'sitefeature/reorder', ['as' => 'sitefeature.reorder', 'uses' => 'SiteFeatureController@reorder']);
        Route::match(['PUT', 'PATCH'], 'sitefeature/{sitefeature}/togglepublish', ['as' => 'sitefeature.togglepublish', 'uses' => 'SiteFeatureController@togglePublish'])->where(['sitefeature' => '[0-9]+']);

        // SiteFeature Backgorund Image
        Route::get('sitefeature/{sitefeature}/image/create/background', ['as' => 'sitefeature.image.create.background', 'uses' => 'SiteFeatureController@createBackground'])->where(['sitefeature' => '[0-9]+']);
        Route::get('sitefeature/{sitefeature}/image/edit/background', ['as' => 'sitefeature.image.edit.background', 'uses' => 'SiteFeatureController@editBackground'])->where(['sitefeature' => '[0-9]+']);

        /////////////////////////////////////////////////////
        // Cateory
        Route::get('category/datatable', ['as' => 'category.datatable', 'uses' => 'CategoryController@dataTable']);
        Route::get('category/tree', ['as' => 'category.tree', 'uses' => 'CategoryController@tree']);
        Route::get('category/search', ['as' => 'category.search', 'uses' => 'CategoryController@search']);
        Route::match(['PUT', 'PATCH'], 'category/{category}/restore', ['as' => 'category.restore', 'uses' => 'CategoryController@restore'])->where(['category' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'category/reorder', ['as' => 'category.reorder', 'uses' => 'CategoryController@reorder']);
        // Cateory Hero Banner Images
        Route::get('category/{category}/image/create/hero-banner', ['as' => 'category.image.create.hero', 'uses' => 'CategoryController@createHeroBanner'])->where(['category' => '[0-9]+']);
        // Category Products
        Route::get('category/{category}/product', ['as' => 'category.product.index', 'uses' => 'CategoryController@products'])->where(['category' => '[0-9]+']);

        /////////////////////////////////////////////////////
        // FeatureSet
        Route::get('featureset/datatable', ['as' => 'featureset.datatable', 'uses' => 'FeatureSetController@dataTable']);
        Route::get('featureset/search', ['as' => 'featureset.search', 'uses' => 'FeatureSetController@search']);
        Route::get('featureset/sort', ['as' => 'featureset.sort', 'uses' => 'FeatureSetController@sort']);
        Route::match(['PUT', 'PATCH'], 'featureset/{featureset}/restore', ['as' => 'featureset.restore', 'uses' => 'FeatureSetController@restore'])->where(['featureset' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'featureset/reorder', ['as' => 'featureset.reorder', 'uses' => 'FeatureSetController@reorder']);
        // FeatureSet Features
        Route::get('featureset/{featureset}/feature', ['as' => 'featureset.feature.index', 'uses' => 'FeatureSetController@features'])->where(['featureset' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'featureset/{featureset}/feature/reorder', ['as' => 'featureset.feature.reorder', 'uses' => 'FeatureSetController@reorderFeatures'])->where(['featureset' => '[0-9]+']);

        /////////////////////////////////////////////////////
        // Product
        Route::get('product/datatable', ['as' => 'product.datatable', 'uses' => 'ProductController@dataTable']);
        Route::get('product/search', ['as' => 'product.search', 'uses' => 'ProductController@search']);
        Route::match(['PUT', 'PATCH'], 'product/{product}/restore', ['as' => 'product.restore', 'uses' => 'ProductController@restore'])->where(['product' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'product/{product}/togglepublish', ['as' => 'product.togglepublish', 'uses' => 'ProductController@togglePublish'])->where(['product' => '[0-9]+']);
        // Product Images
        Route::get('product/{product}/image', ['as' => 'product.image.index', 'uses' => 'ProductController@images'])->where(['product' => '[0-9]+']);
        Route::get('product/{product}/image/create/large', ['as' => 'product.image.create.large', 'uses' => 'ProductController@createLargeImage'])->where(['product' => '[0-9]+']);
        Route::get('product/{product}/image/create/thumbnail', ['as' => 'product.image.create.thumbnail', 'uses' => 'ProductController@createDisplayThumbnail'])->where(['product' => '[0-9]+']);
        Route::get('product/{product}/image/create/shareImage', ['as' => 'product.image.create.shareimage', 'uses' => 'ProductController@createShareImage'])->where(['product' => '[0-9]+']);
        // Product Categories
        Route::get('product/{product}/category', ['as' => 'product.category.index', 'uses' => 'ProductController@categories'])->where(['product' => '[0-9]+']);
        // Product Features
        Route::get('product/{product}/feature', ['as' => 'product.feature.index', 'uses' => 'ProductController@features'])->where(['product' => '[0-9]+']);

        /////////////////////////////////////////////////////
        // Variants
        Route::match(['PUT', 'PATCH'], 'product/{product}/variant/reorder', ['as' => 'product.variant.reorder', 'uses' => 'VariantController@reorder'])->where(['procuct' => '[0-9]+']);
        Route::get('product/{product}/variant/datatable', ['as' => 'product.variant.datatable', 'uses' => 'VariantController@dataTable'])->where(['procuct' => '[0-9]+']);
        Route::match(['PUT', 'PATCH'], 'product/{product}/variant/{variant}/restore', ['as' => 'product.variant.restore', 'uses' => 'VariantController@restore'])->where(['procuct' => '[0-9]+', 'variant' => '[0-9]+']);

        /////////////////////////////////////////////////////
        // Feature
        Route::get('feature/search', ['as' => 'feature.search', 'uses' => 'FeatureController@search']);

app/Models/Category.php
<?php
namespace Okuma\Models;

use Carbon\Carbon;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;
use Franzose\ClosureTable\Contracts\EntityInterface;
use Franzose\ClosureTable\Models\Entity;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;
use Okuma\Models\Category;
use Okuma\Models\Feature;
use Okuma\Models\FeatureSet;
use Okuma\Models\Product;
// use Nicolaslopezj\Searchable\SearchableTrait;
use Sofa\Eloquence\Eloquence;

class Category extends Entity implements EntityInterface, SluggableInterface
{

    use Eloquence;
    // use SearchableTrait;
    use SluggableTrait;
    use SoftDeletes;

    protected $productCount = 0;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'categories';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    // protected $guarded = ['id', 'created_at', 'updated_at', 'deleted_at'];
    protected $guarded = ['id', 'deleted_at'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    // protected $dates = ['created_at', 'updated_at', 'deleted_at'];
    protected $dates = ['deleted_at'];

    /**
     * The class name to be used in polymorphic relations.
     *
     * @var string
     */
    // protected $morphClass = 'Category';

    /**
     * All of the relationships to be touched.
     * would result in too many updates
     * @var array
     */
    // protected $touches = ['products'];

    /**
     * The atrributes that detfine this Model's Slug management
     *
     * @var array
     */
    protected $sluggable = array(
        'build_from' => 'name',
        'on_update' => true,
    );

    /**
     * Searchable rules.
     * jarektkaczyk/eloquence
     *
     * @var array
     */
    protected $searchableColumns = [
        'name' => 20,
        'slug' => 10
    ];

    /**
     * ClosureTable model instance.
     *
     * @var CategoryClosure
     */
    protected $closure = CategoryClosure::class;

    public function heroBanner()
    {
        return $this->morphOne(Image::class, 'imageable');
        // ->select('images.id', 'images.title', 'images.path', 'images.type', 'images.width', 'images.height', 'images.position', 'images.imageable_id', 'images.imageable_type')
        // ->where('images.type', '=', 'category_hero');
        // ->orderBy('images.position', 'asc');
    }

    public function searchThumbnail()
    {
        return $this->morphOne(Image::class, 'imageable')
            ->select('images.id', 'images.title', 'images.path', 'images.type', 'images.width', 'images.height', 'images.position', 'images.imageable_id', 'images.imageable_type')
            ->where('images.type', '=', 'category_search_thumbnail');
    }

    public function products()
    {
        return $this->belongsToMany(Product::class, 'product_categories', 'category_id', 'product_id')
            ->withPivot(['product_position']);
    }

    public function featureSets()
    {
        return $this->belongsToMany(FeatureSet::class, 'category_features', 'category_id', 'feature_set_id');
    }

    public function features()
    {
        return $this->belongsToMany(Feature::class, 'category_features', 'category_id', 'feature_id');
    }

    public function ancestors()
    {
        return $this->belongsToMany(Category::class, 'category_closure', 'descendant', 'ancestor')
            ->withPivot(['ancestor', 'descendant', 'depth']);
        // ->where('depth', '>', 0);
    }

    public function decendants()
    {
        return $this->belongsToMany(Category::class, 'category_closure', 'ancestor', 'descendant')
            ->withPivot(['ancestor', 'descendant', 'depth']);
    }

    public function rootParent()
    {
        return $this->belongsToMany(Category::class, 'category_closure', 'descendant', 'ancestor')
            ->where('categories.real_depth', '=', 0)
            ->limit(1);
    }

    public function getRootParentAttribute()
    {
        // if relation is not loaded already, let's do it first
        if (!array_key_exists('RootParent', $this->relations)) {
            $this->load('RootParent');
        }

        return $this->getRelation('RootParent')->first();
    }

    public function directAncestor()
    {
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

    public function directDecendants()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
        // ->orderBy('position', 'ASC');
    }

    public function productsCount()
    {
        return $this->belongsToMany(Product::class, 'product_categories', 'category_id', 'product_id')
            ->select('category_id')
            ->selectRaw('IFNULL(COUNT(product_id), 0) AS value')
            ->groupBy('category_id');
    }

    public function getProductsCountAttribute()
    {
        // if relation is not loaded already, let's do it first
        if (!array_key_exists('productsCount', $this->relations)) {
            $this->load('productsCount');
        }

        $related = $this->getRelation('productsCount')->first();

        // then return the count directly
        return is_null($related) ? 0 : (int) $related->value;
    }

    public function getTotalProductsCountAttribute()
    {
        return $this->productCount;
    }

    public function setTotalProductsCountAttribute($value)
    {
        if (isset($value) && is_int($value) && $value > 0) {
            $this->productCount = $value;
        }
    }

    public function fetchTotalProductsCount()
    {
        $id = $this->id;

        $productCount = DB::table('categories')
            ->selectRaw('COUNT(DISTINCT okuma_products.id) AS product_count')
            ->join('category_closure', 'category_closure.descendant', '=', 'categories.id')
            ->join('product_categories', 'categories.id', '=', 'product_categories.category_id')
            ->join('products', 'products.id', '=', 'product_categories.product_id')
            ->where('category_closure.ancestor', '=', $id)
            ->whereNull('categories.deleted_at')
            ->whereNull('products.deleted_at')
            ->whereDate('products.published_at', '<=', Carbon::now())
            ->first();

        $this->setTotalProductsCountAttribute($productCount->product_count);

        return $productCount->product_count;
    }

    public static function fetchAllTotalProductCounts()
    {
        $results = DB::table('products')
            ->select('category_closure.ancestor AS category_id', DB::raw('COUNT(DISTINCT okuma_products.id) AS product_count'))
            ->join('product_categories', 'product_categories.product_id', '=', 'products.id')
            ->join('categories', 'product_categories.category_id', '=', 'categories.id')
            ->join('category_closure', 'category_closure.descendant', '=', 'categories.id')
            ->whereNull('categories.deleted_at')
            ->whereNull('products.deleted_at')
            ->whereDate('products.published_at', '<=', Carbon::now())
            ->groupBy('category_closure.ancestor')
            ->get();

        $categoryProductCounts = [];

        foreach ($results as $row) {
            $categoryProductCounts[$row->category_id] = $row->product_count;
        }

        return $categoryProductCounts;
    }
}

resources/views/pages/article.blade.php
@extends('layouts.master')

@section('pageTitle', 'About')

@section('bodyClass', 'article-page')

@section('mastheadContent')
<div class="page-header-strip">
	<div class="row valign-middle">
		<div class="small-12 columns">
			<h1 >About Okuma</h1>
		</div>
	</div>
</div>
@endsection

@section('bodyContent')
	<div class="row">
		<div class="small-12 large-9 small-centered columns"  itemprop="articleBody">

			<article class="product" itemscope itemtype="http://schema.org/BlogPosting">

				<header>
					<div class="row">
						<div class="small-12 large-9 small-centered columns"  itemprop="articleBody">
							<h2 itemprop="headline">About Okuma</h2>
						</div>
					</div>
				</header>

				<section>
						<p>The jolting sound of the clicker; the subtle take of the fly; the crushing strike that comes on a fast-retrieved swimbait-- fishing rewards the senses in so many ways. From mountain lake to offshore waters, at every turn Okuma Fishing Tackle embraces your passion for the sport of fishing.</p>

						<p>Our 2015 introductions continue our commitment to dynamic and innovative rods and reels for both freshwater and saltwater anglers. Within each, our goal is to advance your skills and deliver a better experience from every day on the water. We accomplish this with advanced materials, cutting-edge design and by having one ear to the ground at all times. Our customers are the source of our most valuable input and it's your needs, goals and desires the drive Okuma product development.</p>
				</section>
				<section>
				</section>

			</article>

		</div>
	</div>
@endsection

@section('scripts')
@endsection

resources/views/pages/catalog.blade.php
@extends('layouts.master')

@section('pageTitle', 'Catalog')

@if(!is_null($catalog->snippet))
	@section('pageDescription', $catalog->snippet)
@endif

@section('bodyClass', 'catalog-page')

<?php $hasHeroBanner = isset($catalog->heroBanner);?>

@if($hasHeroBanner)
	@section('mastheadClass', 'has-hero-image')
@endif

@section('mastheadContent')
	@if($hasHeroBanner)
		<div class="hero-image" style="background-image: url({{ url($catalog->heroBanner->path) }});"></div>
	@endif

	<div class="page-header-strip">
		<div class="row valign-middle">
			<div class="small-12 columns">
				<p class="text-center">{{ $catalog->description }}</p>
			</div>
		</div>
	</div>
@endsection

@section('bodyContent')
	<div class="category-content">
		@foreach ($catalog->children as $category)
			@if ($category->total_products_count > 0)

				<div class="row"  id="category-{{ $category->slug }}">
					<div class="medium-12 large-3 columns">
						<div class="catalog-category-details">
							<h2><a href="{{ route('category', ['slug'=>$category->slug]) }}">{{ $category->name }}</a></h2>
							<a href="{{ route('category', ['slug'=>$category->slug]) }}" class="animated-link bg-block bg-skew-anim">
								View all <strong>{{ $category->product_count }}</strong> {{ $category->name }} <span class="icon-right-circle"></span>
							</a>
						</div>
					</div>

					<div class="medium-12 large-9 columns">
						<div class="row">
							<?php $columnSize = 'small-6 medium-4 large-3';?>
							@foreach ($category->products as $product)
								@include('components.productblock')
							@endforeach
						</div>
					</div>
				</div>

			@endif
		@endforeach
	</div>
@endsection

resources/views/pages/category.blade.php
@extends('layouts.master')

@section('pageTitle', 'Category | '.$category->name)

@if(!is_null($category->snippet))
@section('pageDescription',$category->snippet)
@endif

@section('bodyClass', 'category-page')

<?php $hasHeroBanner = isset($category->heroBanner);?>

@if($hasHeroBanner)
@section('mastheadClass', 'has-hero-image')
@endif

@section('mastheadContent')
@if($hasHeroBanner)
	<div class="hero-image" style="background-image: url({{ url($category->heroBanner->path) }});">
	</div>
@endif

<div class="page-header-strip">
	<div class="row valign-middle">
		<div class="small-12 medium-4 columns">
			<h1 class="medium-text-right">{{ $category->name }}</h1>
		</div>
		<div class="small-12 columns show-for-medium-up">
			<p>{{ $category->description }}</p>
		</div>
	</div>
</div>
@endsection

@section('bodyContent')
<div class="catalogue-content">
	<div class="row">
		<div class="small-12 medium-3 columns">
			<aside>@include('components.sidebar_fitler_menu')</aside>
		</div>
		<div class="small-12 medium-9 columns">
			<section id="category-products">
				<div class="row">
					<?php $columnSize = 'small-6 medium-4';?>
					@foreach($products as $product)
						@include('components.productblock')
					@endforeach
				</div>
			</section>
		</div>
	</div>

	@if($products->hasPages() )
	<div class="row">
		<div class="small-12 medium-9 columns medium-push-3">
			<div class="pagination-centered">
				{{-- {!! $products->appends(Request::except('page'))->render() !!} --}}
				{!! $products->appends(Request::except('page'))->render(new Okuma\Pagination\FoundationPresenter($products) ) !!}
			</div>
		</div>
	</div>
	@endif
</div>
@endsection

@section('scripts')
<script type="text/javascript" src="{{ elixir('js/okuma/category.js') }}"></script>
@endsection

resources/views/pages/competition.blade.php
<h1>Competition</h1>

resources/views/pages/contact.blade.php
@extends('layouts.master')

@section('metaTags')
<meta name="csrf-token" content="{{ csrf_token() }}">
@endsection

@section('pageTitle', 'Contact Us')

@section('pageDescription', 'Get in touch with us at Okuma Inspired Fishing South Africa. Contact us at info@okuma.co.za or give us a call on +27 12 327 1301.')

@section('bodyClass', 'contact-page')

@section('mastheadContent')
<div class="row">
	<div class="small-12 columns">
		<h1 class="title-header">Contact Us</h1>
	</div>
</div>
@endsection

@section('bodyContent')
<div class="contactpage-content">
	<div class="row">
		<div class="small-12 medium-4 columns">
			<section class="contact-info">
				<h3>Okuma Southern Africa</h3>
				<div class="contact-info-block">
					<div><span class="icon icon-email"></span>{{ Config::get('okuma.contact.email') }}</div>
					<div><span class="icon icon-phone"></span> +27 10 591 2987 / 6</div>
					<div><span class="icon icon-location"></span> Cnr. Baralong and Sunbeam Street<br/>
						Icon Park, Sunderland Ridge Industrial<br/>
						Centurion<br/>
						0157<br/>
						South Africa
					</div>
					<div><span class="icon icon-facebook"></span> <a href="https://facebook.com/OkumaFishingAfrica" target="_blank">/OkumaFishingAfrica</a></div>
				</div>
			</section>
		</div>

		@if(Session::has('contact-response') && Session::get('contact-response') === 'sent')
			<div class="small-12 medium-8 columns">
				<p><span class="large-icon size-45 icon-tick bg-success"></span> Thank you! Your message has been sent and we will be in touch with you soon.</p>
			</div>
		@endif

		<div class="small-12 medium-8 columns">
			<section>
				<h3>Contact Form</h3>
				<p>Complete the form below to get in touch with us <em>(All fields are required).</em></p>

				<form method="POST" action="{{ route('contact.request') }}#contact-form" accept-charset="UTF-8" id="contact-form" enctype="application/x-www-form-urlencoded">
					<input type="hidden" name="_token" value="{{ csrf_token() }}">

					<div class="row">
						<div class="small-12 columns">
							<div class="form-input underlined animated">
								<input type="text" name="contact-name" id="contact-name" class="input-field" maxlength="128" value="{{ old('contact-name') }}" autocomplete="off" />
								<label class="input-label" for="contact-name">
									<div class="input-label-value" >Name <span id="error-name">{!! $errors->contact->first('contact-name', '<span class="feedback-message"><i class="icon-attention-circle text-alert"></i> :message</span>') !!}</span></div>
								</label>
							</div>
						</div>
					</div>

					{!! Honeypot::generate('contact-lastname', 'contact-time') !!}

					<div class="row">
						<div class="small-12 columns">
							<div class="form-input underlined animated">
								<input type="text" name="contact-email" id="contact-email"  class="input-field" maxlength="254"value="{{ old('contact-email') }}" autocomplete="off" />
								<label class="input-label" for="contact-email" >
									<div class="input-label-value" >Email <span id="error-email">{!! $errors->contact->first('contact-email', '<span class="feedback-message"><i class="icon-attention-circle text-alert"></i> :message</span>') !!}</span></div>
								</label>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="small-12 columns">
							<div class="form-input underlined animated">
								<input type="text" name="contact-subject" id="contact-subject" class="input-field" maxlength="64"value="{{ old('contact-subject') }}" autocomplete="off" />
								<label class="input-label" for="contact-subject" >
									<div class="input-label-value" >Subject <span id="error-subject">{!! $errors->contact->first('contact-subject', '<span class="feedback-message"><i class="icon-attention-circle text-alert"></i> :message</span>') !!}</span></div>
								</label>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="small-12 columns">
							<div class="form-input text-area underlined animated">
								<textarea name="contact-message" id="contact-message" class="input-field" rows="11" autocomplete="off" >{{ old('contact-message') }}</textarea>
								<label class="input-label" for="contact-message">
									<div class="input-label-value" >Message <span id="error-message">{!! $errors->contact->first('contact-message', '<span class="feedback-message"><i class="icon-attention-circle text-alert"></i> :message</span>') !!}</span></div>
								</label>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="small-12 medium-4 columns small-only-text-center">
							<button type="submit" class="form-control submit button expand ajax-progress-button" id="contact-submit"><span class="icon"></span><strong class="btn-label">Send Message</strong></button>
						</div>
						<div class="small-12 medium-8 columns">
							<span id="error-form"></span>
						</div>
					</div>
				</form>

			</section>
		</div>
	</div>
</div>
@endsection

@section('scripts')
<script type="text/javascript" src="{{ elixir('js/okuma/contact.js') }}"></script>
@endsection

resources/views/pages/homepage.blade.php
@extends('layouts.master')

@section('pageTitle', 'Inspired Fishing')

@section('bodyClass', 'home-page')

@section('mastheadContent')
	@if(isset($hero))
		<div class="hero">
			<div class="site-feature-wrapper">
				<figure class="site-feature {{ $hero->display_class }}" >

					@if(isset($hero->background))
						<div class="site-feature-bg" style="background-image: url({{ URL::asset($hero->background->path) }})"></div>
					@endif

					<figcaption>
						<div class="site-feature-content">
							@if(isset($hero->title))
								<h2 class="site-feature-title">{{ $hero->title }}</h2>
							@endif
							@if(isset($hero->body))
								<div class="site-feature-body">{{ $hero->body }}</div>
							@endif
						</div>

						@if(isset($hero->link))
							<a href="{!! $hero->link !!}" class="site-feature-link"><span>View More</span></a>
							@if(isset($hero->button_label))
								<a href="{!! $hero->link !!}" class="site-feature-button">{{ $hero->button_label }}</a>
							@endif
						@endif
					</figcaption>
				</figure>
			</div>
		</div>
	@endif
@endsection

@section('bodyContent')
	<div class="homepage-content">
		<div class="row collapse">
			@foreach ($siteFeatures as $feature)
				<div class="columns {{ $feature->column_size }}">
					<div class="site-feature-wrapper">
						<figure class="site-feature {{ $feature->display_class }}">

							@if(isset($feature->background))
								<div class="site-feature-bg" style="background-image: url({{ URL::asset($feature->background->path) }})"></div>
							@endif

							<figcaption>
								<div class="site-feature-content">
									@if(isset($feature->title))
										<h2 class="site-feature-title">{{ $feature->title }}</h2>
									@endif
									@if(isset($feature->body))
										<div class="site-feature-body">{{ $feature->body }}</div>
									@endif
								</div>

								@if(isset($feature->link))
									<a href="{!! $feature->link !!}" class="site-feature-link"><span>View More</span></a>
									@if(isset($feature->button_label))
										<a href="{!! $feature->link !!}" class="site-feature-button">{{ $feature->button_label }}</a>
									@endif
								@endif
							</figcaption>
						</figure>
					</div>
				</div>
			@endforeach
		</div>
	</div>
@endsection